; ----------------------------------
; START HEADER
; This will define a string, calculate its length, and print it.

SECTION .data
; END HEADER
; ----------------------------------
msg     db      'this is the print string generated by your compiler', 0Ah     ; 

; ----------------------------------
; START FOOTER

SECTION .text
global  start

start:
    mov     rdi, msg
    mov     rax, rdi
.nextchar:
    cmp     byte [rax], 0
    jz      .finished
    inc     rax
    jmp     .nextchar
.finished:
    sub     rax, rdi
    mov     rdx, rax
    mov     rsi, msg
    mov     rdi, 1
    mov     rax, 0x2000004
    syscall
    mov     rdi, 0
    mov     rax, 0x2000001
    syscall

; END FOOTER
; ----------------------------------